#!/bin/bash
xcompmgr &
guake &
avant-window-navigator &
volti &
parcellite &
pasystray &
tint2 &
nm-applet &
nitrogen --restore &
claws-mail &
pidgin &
thunar --daemon &
dropbox &
qbittorrent &
xscreensaver &
skype &
conky -c /home/eraindil/.conky/conkyrc &
