#!/bin/bash
xcompmgr &
guake &
avant-window-navigator &
parcellite &
tint2 &
nitrogen --restore &
claws-mail &
pidgin &
thunar --daemon &
dropbox &
volti &
xscreensaver &
skype &
conky -c /home/eraindil/.conky/conkyrc &
